### ISSUE TITLE
[Request] Could you make a Permission for this command - LuckPerms

### ISSUE THREAD

**Issue by xR4YM0ND** [Giggitybyte/Aliases#1]
Hey there, 

couldnt comment down below so i make a request here.

Could you make it compatible with LuckPerms Permissions API ? 

just a simple permission for this /aliases command 

When a person or group has this permission ( example: aliases.command ) they are allowed to check for aliases 

https://github.com/lucko/fabric-permissions-api

**Comment by xR4YM0ND** [comment]
https://www.curseforge.com/minecraft/mc-mods/luckperms

**Comment by Giggitybyte** [comment]
Sure! I'll implement what is needed in a day or so when I have some free time

**Comment by Giggitybyte** [comment]
New version has been released; let me know if there are any issues!
https://www.curseforge.com/minecraft/mc-mods/aliases/files/3750920

**Comment by xR4YM0ND** [comment]
Perfect <3 Works as intended. Thank you
